version: '3'
services:
  main_jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
       - 8080:8080
       - 5000:5000   
  agent:
    container_name: agent
    build:
      context: .
      dockerfile: ./Dockerfile_agent_jenkins
    image: agent
